### PR TITLE
DeprecationWarning: formatargspec

### LINKED ISSUE #127: Deprecation warning for formatargspec in Python3.7
Minor issue:
`
python3.7/site-packages/asyncio_redis/protocol.py:549: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
`

### PR DESCRIPTION
**Pull request by crusaderky**
Closes #127

### CODE REVIEW

**Comment by crusaderky** [comment]
Manually tested in Python 3.4.5 and 3.7.4 to produce identical output to the previous implementation.

All CI tests successful, except on Python 3.3 which is not available for download in travis anymore.
I could not find an easy way to manually test on Python 3.3, as the MacOSX installer doesn't seem to work anymore either.

I would advise dropping support for Python <3.5 anyway as the percentage of users still stuck on such ancient versions is negligible.

**Comment by crusaderky** [comment]
@jonathanslenders ping

**Comment by crusaderky** [comment]
@jonathanslenders are you still maintaining this project?

**Comment by jonathanslenders** [comment]
Thank you @crusaderky, for the reminder!

I'm indeed not actively maintaining the project due to priorities, but all fixes and trivial improvements are very welcome.
(If there is anyone with time available to take over maintenance + handling GitHub issues and PRs, that'd be nice too. ;) )

**Pull request merged**
